services:
  postgres:
    image: postgres:15
    container_name: retail_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retaildb
    ports:
      - "5432:5432"
    volumes:
      - D:/rms_postgres_data:/var/lib/postgresql/data

  auth-service:
    container_name: retail_auth_service
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  
  product-service:
    container_name: retail_product_service
    build:
      context: .
      dockerfile: apps/product-service/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  web-app:
    container_name: retail_web_app
    build:
      context: .
      dockerfile: apps/web-app/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - product-service   

  nginx:
    image: nginx:alpine
    container_name: retail_nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-app
      - auth-service
      - product-service   